CyberLife/Controllers/AjaxController.cs
using CyberLife.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CyberLife.Controllers;

public class AjaxController : Controller
{
    
    public static Dictionary<string, Map> Maps = new Dictionary<string, Map>();
    public static IList<string> Session = new List<string>();
    
    public IActionResult Restart()
    {
        Map map = Maps[HttpContext.Session.GetString(HttpContext.Session.Id)];
        Maps[HttpContext.Session.GetString(HttpContext.Session.Id)] = new Map(map.Width, map.Height, map.WidthBiome, map.SizeBiome, map.BotSpawnChance);
        return Redirect("Start");
    }
    
    [Authorize]
    [HttpPost]
    public IActionResult SetMapParameters(int width = 78, int height = 40, int widthBiome = 30, int sizeBiome = 300, int botSpawnChance = 50)
    {
        Maps[HttpContext.Session.GetString(HttpContext.Session.Id)] = new Map(width, height, widthBiome, sizeBiome, botSpawnChance);
        return Redirect("Start");
    }
    
    public IActionResult Main()
    {
        if (!Maps.ContainsKey(HttpContext.Session.Id))
        {
            HttpContext.Session.SetString(HttpContext.Session.Id, HttpContext.Session.Id);
            Session.Add(HttpContext.Session.Id);
            Maps.Add(HttpContext.Session.Id, new Map());
        }
        return View(Maps[HttpContext.Session.GetString(HttpContext.Session.Id)]);
    }
    
    public IActionResult Start()
    {
        Maps[HttpContext.Session.GetString(HttpContext.Session.Id)].Work(HttpContext.Session.GetString(HttpContext.Session.Id));
        return View(Maps[HttpContext.Session.GetString(HttpContext.Session.Id)]);
    }

}

CyberLife/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Симулятор эволюции | CyberLife</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/grid.css">
    <link rel="stylesheet" href="~/CyberLife.styles.css" asp-append-version="true"/>
    <script src="~/lib/Ajax/jquery.unobtrusive-ajax.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
    <script src="~/js/Aja.js"></script>
    <script src="~/lib/Ajax/jquery-3.6.1.js"></script>
    <script src="https://kit.fontawesome.com/5eaff8a265.js" crossorigin="anonymous"></script>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm mb-3 box-shadow">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="About"><img src="/logo.png" height="50px" alt=""></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1 mt-2">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">О проекте</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Ajax" asp-action="Main">Мир</a>
                    </li>
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Trends">Графики</a> *@
                    @* </li> *@
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>

<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="box-shadow footer text-muted mt-5">
    <div class="container">
        &copy; 2022 - Симулятор эволюции | CyberLife - <a asp-area="" asp-controller="Home" asp-action="Privacy">Политика конфиденциальности</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>